# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: My Portfolio
email: info@extau.com
description: > # this means to ignore newlines until "baseurl:"
  Jannik Richter, jannik811@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://extau.github.io" # the base hostname & protocol for your site
twitter_username: sir_kapil_ch
github_username:  extau

# Build settings
markdown: kramdown
